guybedford/es-module-shims

src/common.js, test/base-href.js, test/fixtures/es-modules/base-href-bare.js, test/fixtures/es-modules/base-href-relative.js, test/test-base-href.html
The same change as: https://github.com/systemjs/systemjs/pull/1957 to solve the issue described here: https://github.com/systemjs/systemjs/issues/1956
=> Take base href into account when resolving relative urls

src/common.js
This updates the import map resolution to the latest SystemJS approach in resolving all the map targets early, instead of as they are resolved, fixing https://github.com/guybedford/es-module-shims/issues/31 in the process.
=> Early import map resolution

README.md, src/es-module-shims.js, test/browser-modules.js, test/fixtures/style.css, test/test.html
This provides a CSS modules implementation as described in https://github.com/guybedford/es-module-shims/issues/40.
=> Implement CSS modules

README.md
Finally got around to this, resolves #34.
=> Add compatibility tables

src/es-module-shims.js
Fixes https://github.com/guybedford/es-module-shims/issues/54.
@costingeana I would still value your input on what servers you found were producing this content type.
=> Support x-javascript MIME

README.md
If you reject this PR I would not be offended.  Just was reading the readme and noticed the out of date number at the top, figured I would PR a quick-fix.
=> Gotta keep the stats up to date!

src/common.js, src/es-module-shims.js
Includes an implementation for depcache, as discussed in the SystemJS PR - https://github.com/systemjs/systemjs/pull/2134.
=> depcache implementation

src/common.js, test/browser-modules.js, test/fixtures/es-modules/import-relative-path.js, test/test.html
=> Support URL to URL mappings

src/common.js, src/es-module-shims.js, test/browser-modules.js, test/test.html
This refines some of the top-level state handling added in https://github.com/guybedford/es-module-shims/pull/109, and also fixes up a double top-level execution case (https://github.com/guybedford/es-module-shims/issues/111).
=> State adjustments, fixup top-level exec

src/es-module-shims.js, test/shim.html
Fixes a regression in the shim mode processing.
=> fix: fixup shim mode execution

CONTRIBUTING.md, package.json, rollup.config.js, src/es-module-shims.js, test/browser-modules.js, test/fixtures/es-modules/with-absolute-source-mapping-url.js, test/fixtures/es-modules/with-relative-source-mapping-url.js, test/fixtures/es-modules/with-relative-source-mapping-url.js.map, test/fixtures/es-modules/with-relative-source-mapping-url.ts, test/fixtures/es-modules/with-relative-source-url.js, test/fixtures/es-modules/without-source-url.js, test/perf.html, test/server.mjs, test/test.html
Also added rollup config and CONTRIBUTING.md.
=> Handle relative sourceURL and sourceMappingURL

.github/FUNDING.yml, .travis.yml
Sets up Travis CI with testing in Firefox.
=> Add travis run and sponsorship badge

src/es-module-shims.js
Fixes a bug on minified sources where changing the end index to the statement end no longer needs the offset.
=> Fixup end index in source rewriting

index.d.ts, package.json
Completely forgot we have a TypeScript definition.
This should update it to the latest API.
=> Fixup types

src/es-module-shims.js
This institutes a fetch pool of 100 fetch requests, which improves loading performance for large numbers of modules (1000s).
=> Implement fetch pool

src/es-module-shims.js
This fixes up some of the finer lifecycle handling details associated with the native passthrough performance work.
In particular:
* Shim mode must be immediately known on intialization, there is no longer any concept of a "deferred shim mode". This is what the shim mode option is for.
* When in native passthrough mode, preloads are never triggered, but import maps specifically are checked until they have been locked down, per https://github.com/guybedford/es-module-shims/pull/196.
* These lifecycle events properly queue against competing loads.
=> fix: lifecycle handling and import maps waiting

package.json
Updates with better memory management per https://github.com/guybedford/es-module-lexer/pull/88. Resolves https://github.com/guybedford/es-module-shims/issues/202 in supporting large module sources.
=> deps: update to es-module-lexer@0.9.1

package.json, test/server.mjs, test/test-dom-order.html
Follow-up fix for https://github.com/guybedford/es-module-shims/pull/221 as the test wasn't being run.
=> fix: dom ordering test

src/es-module-shims.js
This adds a step to wrap the fetch error message with the fetch context for the error. Normally `fetch()` errors do not report the URL they fetched for security reasons, instead providing a separate network log. This adds the first line of the URL with a note to check the network log for that URL. In addition we also pipe through the parent importer context to be able to tell where the fetch was first initiated.
=> feat: fetch error details with context

README.md
Fixes https://github.com/guybedford/es-module-shims/issues/259
=> Clarify use of modulepreload-shim

package.json
Fixes another possible memory overflow issue from the asm.js build.
=> deps: update to es-module-lexer@0.10.4

src/env.js
Resolves https://github.com/guybedford/es-module-shims/issues/278.
=> fix: skip userAgent when userAgentData

test/runMochaTests.js, test/server.mjs
Getting no feedback from headless tests makes it difficult to support
multiple browsers.
Moving to use Karma would be another possibility: https://karma-runner.github.io/latest/index.html
=> tests: send test results back to the test server.

chompfile.toml, package.json, src/es-module-shims.js, test/fixtures/test-self-import.js, test/server.mjs, test/shim.js
Upgrades to es-module-lexer 1.0.0. For returning exports as ExportSpecifier[].
Based on @guybedford's #296.
Closes #295.
=> fix: self imports.

package.json
Fixes the parser error reported in https://github.com/guybedford/es-module-shims/issues/315 via https://github.com/guybedford/es-module-lexer/pull/128.
=> deps: update to es-module-lexer@1.0.2

README.md
Updates the compat table to latest compat, and adjust some of the notes on worker support.
=> docs: update compat table, worker support info

src/features.js
This implements a possible fix for WeChat browser support. Fixes https://github.com/guybedford/es-module-shims/issues/329.
=> fix: WeChat browser srcdoc support

src/resolve.js
Resolves https://github.com/guybedford/es-module-shims/issues/334, fixing the regression from https://github.com/guybedford/es-module-shims/pull/268.
=> fix: hash-relative resolution

src/env.js, src/es-module-shims.js
Moreover, skip code for Regexp was incorrect (s and r variables were inverted)
=> Fix: New skip implementation was incorrectly called

index.d.ts
fix: missing fields for ESMSInitOptions type
=> fix: missing fields for ESMSInitOptions type

package.json
Updates to the latest es-module-lexer@1.0.5.
=> deps: update to es-module-lexer@1.0.5

src/es-module-shims.js, test/test-load-event.html
Closes https://github.com/guybedford/es-module-shims/issues/346
=> fix: fixed the load event of "module-shim" scripts

README.md
=> Remove one of the two "entirely"s in a phrase

src/es-module-shims.js
Here's the start of a WASM support patch that (lest anyone assume I knew what I was doing) was designed & implemented by @guybedford. I did at least adjust it so it worked for me!
From here, I imagine a proper implementation would mostly involve adding some tests. I didn't want this code to get lost so I'm pushing it up as a draft for now in case anyone else is interested.
=> WASM support

src/es-module-shims.js, src/resolve.js
This should resolve the issue brought up in https://github.com/guybedford/es-module-shims/issues/397.
=> Fix unnormalized url normalization

src/es-module-shims.js
Adds support for `fetchpriority` on script elements.
=> feat: support script fetchPriority

package.json
Updates to the latest es-module-lexer release.
=> deps: update to latest es-module-lexer

README.md
This further updates the docs and compat tables to be a little more up-to-date.
=> docs: update readme compat table

.github/workflows/ci.yml, .prettierrc, chompfile.toml, package.json, src/dynamic-import.js, src/env.js, src/es-module-shims.js, src/features.js, src/resolve.js
Applies Prettier to the codebase for standard formatting.
=> feat: add prettier

package.json
Updates to es-module-lexer@1.6.0.
=> deps: update to es-module-lexer@1.6.0

src/env.js
Fixes a bug with the TS loader auto-loading from JSPM URLs.
=> fix: ts loader location

src/env.js
Per https://github.com/guybedford/es-module-shims/issues/465
=> fix: document check for tsTransform for worker support

src/es-module-shims.js
Resolves https://github.com/guybedford/es-module-shims/issues/475.
=> fix: typo bug

src/es-module-shims.js
Removes a debug log from the 2.1.0 work branch.
=> fix: debug log

README.md, src/env.js, src/es-module-shims.js, src/hot-reload.js, test/fixtures/dep.ts, test/hot.js, test/test-hot.html
This fixes support for hot-reloading inline scripts including support for TypeScript.
=> Hot reload fix

.github/workflows/ci.yml, src/core.js, test/fixtures/json-ld.js, test/fixtures/json-ld.jsonld, test/server.mjs, test/shim.js
adds support for json-ld and similar `*/*+json` formats (as per the html spec) and makes this function a few bytes smaller minzipped
=> support */*+json (ex. json-ld)
