guybedford/es-module-shims

- dist/es-module-shims.js
- src/common.js
- test/browser-modules.js
Potential fix for #6 
* Supports `http(s):`, `data:`, and `blob:` urls.
* Adds tests for `http(s):`, `data:`, and `blob:` urls.
> support non-relative URLs with protocol

- README.md
- src/es-module-shims.js
- test/browser-modules.js
- test/fixtures/json-error.json
- test/fixtures/json.json
This implements loading of json modules, as in the WhatWG spec.
Again, we use file extensions as the signifier, which while not strictly spec compliant is a good enough heuristic for the polyfill.
> Implement json modules

- src/common.js
- src/es-module-shims.js
- test/browser-modules.js
- test/fixtures/es-modules/built-in-fallback.js
- test/test.html
Regarding this issue: https://github.com/guybedford/es-module-shims/issues/19 Would this suffice to support fallbacks for now? This should always resolve the fallback instead of the built-in module, as you suggested in that issue. Please let me know your thoughts on this :-) Would happily take some pointers
> support fallback imports from import map

- src/common.js
- test/browser-modules.js
- test/fixtures/es-modules/query-param-a.js
- test/fixtures/es-modules/query-param-b.js
When you import a module with query parameters or hashes it incorrectly imports dependencies as it's trying to join the paths including the query parameters and hashes. Stripping them before resolving, just like with the page base path, fixes this.
> fix importing modules with path segments

- src/es-module-shims.js
I made this change locally per recommendation in #4 and it seems to resolve the problem.  I also tested in Chrome, which appeared to work for me.
Breakpoints in Firefox still don't work from within source maps, but I think that is a Firefox bug, not an issue with this library.
I recommend having either CI or another human manually test this change.  I have no idea what I'm doing and just took the code referenced in #4 and pasted it verbatim.
Fixes #4
> Fixes source mapping in Firefox.

- src/common.js
- src/es-module-shims.js
This provides a lastIndex optimization for the regex approach. The remaining `new URL` call is still quite expensive and would benefit from using the internal resolver too.
If the URL implementation can be fixed, that gets the time down to about 0.1ms per 500KiB over 1ms per 500KiB, but without that the improvement to ~0.7ms doesn't yet seem worthwhile.
> Optimize sourcemap detection

- README.md
- package.json
- src/es-module-shims.js
- test/perf.html
This upgrades to the latest es-module-lexer, which now uses Web Assembly for the analysis. We still retain a single-file .js build at the cost of an extra 2KiB, but the win is 6x improvement in cold start performance, which improves the performance from over 100ms for multiple megabytes of JS analysis to down to under 50ms!
> Upgrade to latest Wasm es-module-lexer

- src/common.js
- src/es-module-shims.js
- src/worker-shims.js
- test/browser-modules.js
This updates to the latest cascading import maps implementation as in SystemJS at https://github.com/systemjs/systemjs/pull/2009.
In addition a proper fallback for kv-storage is supported now too, so that fallbacks can be used to actually load this builtin module in Chrome or its polyfill otherwise.
Resolves #48.
> Cascading import maps implementation

- README.md
- src/es-module-shims.js
- test/browser-modules.js
This provides strict Content-Type checking for all module types, aligning with the modules specification properly.
This is important to be correct semantically over using file extensions.
Resolves #42.
> Strict content-type checks

- src/es-module-shims.js
Extends the MIME checking to support `text/javascript`.
Resolves #52.
> Support text/javascript MIME

- README.md
- src/es-module-shims.js
- test/browser-modules.js
- test/fixtures/es-modules/_a.js
- test/fixtures/es-modules/_b.js
- test/fixtures/es-modules/_c.js
- test/fixtures/es-modules/_d.js
- test/fixtures/es-modules/_e.js
- test/fixtures/es-modules/_f.js
- test/fixtures/es-modules/_g.js
- test/fixtures/es-modules/_h.js
- test/fixtures/es-modules/_i.js
- test/fixtures/es-modules/a.js
- test/fixtures/es-modules/b.js
- test/fixtures/es-modules/c.js
- test/fixtures/es-modules/exec-order-a.js
- test/fixtures/es-modules/exec-order-b.js
- test/fixtures/es-modules/exec-order-c.js
- test/fixtures/es-modules/exec-order.js
- test/fixtures/es-modules/s.js
- test/test.html
This fixes the Edge bug discovered in https://github.com/guybedford/es-module-shims/pull/55.
I wasn't sure if this would be possible but incredibly luckily it turned out to be!
The approach basically inlines the execution order into the graph, specifically for Edge support and only in Edge browsers.
The cost is about 40 bytes to the footprint of the project but it seems worth it.
> Fix edge execution ordering bug

- src/common.js
- src/es-module-shims.js
This reworks the standard module checks in fallbacks to be lazy to avoid unnecessary console errors.
In addition direct imports of standard modules have been fixed to work correctly too.
> Std module reworking

- src/es-module-shims.js
...this improves detection. Admittedly, this doesn't exactly meet source map standard (which claims that `//# sourceMappingURL` must be "at the end of the file", but at least this meets browsers' behavior (checked with Firefox and Chrome) - they have no problems attempting to load source map even if mapping is in the middle of the file.
The basic idea is to pick last `//# sourceMappingURL=` from the file and then treat anything after `=` and until line feed or end of file as URL. This last part matches browsers' behavior as well.
Based on last discussion in this issue: https://github.com/guybedford/es-module-shims/issues/4
> sourceMappingURL replacement may be easily broken by extra line breaks

- src/es-module-shims.js
Fixes https://github.com/guybedford/es-module-shims/issues/86 in ensuring no recursion is possible during the loading phase.
> Only processScripts on first top-level load

- README.md
- src/es-module-shims.js
- test/browser-modules.js
- test/fixtures/es-modules/import-meta-resolve.js
This implements an `import.meta.resolve` function to solve contextual module resolution. It is implemented as to the Node.js `--experimental-import-meta-resolve` implementation.
See the readme docs in the PR for furthe details.
> import.meta.resolve implementation

- src/es-module-shims.js
This removes https://github.com/guybedford/es-module-shims/pull/37 which I've tested in Firefox to no longer be necessary.
//cc @MicahZoltu
> Remove firefox sourceMappingURL rebase

- src/es-module-shims.js
Currently, if any script has been processed previously the `for` loop within `processScripts` function causes the function to return early. 
This is changed to `continue` to allow processing of new `module-shim` and `importmap-shim` scripts when calling `importShim.load()`.
Fixes #103
> Allow scripts to dynamically be added

- README.md
- src/es-module-shims.js
- test/fetch-hook.js
- test/initial-options.js
- test/test-fetch-hook.html
- test/test-initial-options.html
This PR is meant to address the issue brought up in https://github.com/guybedford/es-module-shims/issues/108, whereby the fetch hook doesn't always get applied in time for the first shimmed module load.
We now accept an `importShimInitialOptions` global to apply specific options on initialization instead of the defaults, which can be supplied by the user before es-module-shims is loaded, guaranteeing that they will be applied to the first shimmed module load.
The API `importShimInitialOptions` was inspired by https://github.com/guybedford/es-module-shims/pull/95, but with the `Initial` qualifier added to hopefully avoid misuse since setting it after es-module-shims is loaded doesn't have any effect. The implementation also differs in that it explicitly applies only specific properties …
> Add initial options API

- src/common.js
- test/test.html
This fixes up a bug in scope resolution, where the keys in the scope should resolve relative to the baseUrl not the scopeUrl.
> Resolve scope keys to base url

- README.md
- src/es-module-shims.js
- test/dynamic-import-map-shim.html
- test/dynamic-import-map-shim.js
- test/server.mjs
This draft adds a failing test (`http://localhost:8080/test/dynamic-import-map-shim.html`) for the scenario when an import map is inserted dynamically from JS and `importShim()` that is trying to import a bare module specifier defined in that dynamic import map is called right after the insertion.
In the state after the [first commit](https://github.com/guybedford/es-module-shims/pull/123/commits/6504a33cab7c9e8cd2e153249a4f67ca18dcd867) the code works in Safari and prints the following to the console
but it fails in Chrome with printing the following:
The second commit fixes it.
> Fix immediately added dynamic import maps

- src/es-module-shims.js
- test/browser-modules.js
- test/test.html
Attempting to polyfill a dynamic import in an inline script currently fails with `TypeError: url is undefined`.
`load.r` is only set when the source needs to be fetched, which is not the case for inline scripts.
https://github.com/guybedford/es-module-shims/blob/986733009f4c9374decd4c0348740134ff499157/src/es-module-shims.js#L240-L244
My proposed solution is to rewrite such imports as `importShim("...", undefined)` … which seems to work, as it's gonna default to `pageBaseUrl`.
> Fix dynamic imports in inline scripts

- src/common.js
Fixes https://github.com/guybedford/es-module-shims/issues/127.
In Safari (and Chrome\*), import maps feature detection via a `blob:` iframe fails on null origins (such as `file:`, but I guess it might also fail e.g. in sandboxed iframes) — `parent._$s(v)` fails with a CORS error.
_\* This of course is not really a problem in Chrome, since they support import maps natively anyway. Interestingly enough, it doesn't fail in Firefox, so it looks like Firefox has more lax null origin restrictions?_
This PR proposes to use [`srcdoc`](https://caniuse.com/?search=srcdoc) instead of `src="blob:...` for the iframe, which seems to work.
> Fix supportsImportMaps feature detection on null origins

- .github/workflows/ci.yml
- README.md
- package.json
- src/common.js
- src/es-module-shims.js
- test/browser-modules.js
- test/fixtures/json-assertion.js
This updates es-module-shims to behave as a full JSON modules polyfill or shim.
When an import assertion is encountered, es-module-shims knows to polyfill and reexecute the graph with rewritten sources excluding the new syntax, using es-module-lexer@0.6.0 import assertions support.
* Updates to es-module-lexer@0.6.0 with import assertion parsing
* Rewrites import assertions into normal imports
* Supports JSON source loading
* JSON module assertions are feature detected on initialization, then marked as requiring polyfilling when encountered.
> Support JSON Modules

- README.md
- src/es-module-shims.js
- test/test.html
This adds comprehensive support for polyfilling `<link rel="modulepreload" />`. In addition this PR fixes up the fetch options handling to provide support for exact `crossorigin`, `referrerpolicy` and `integrity` attributes on both module scripts and preload tags.
This enables:
* Preloading `modulepreload` for shimmed and non-shimmed modes in non Chromium browsers
* Integrity for all modules via `modulepreload` shimmed and unshimmed, polyfilled and unpolyfilled in all browsers.
> feat: support modulepreload polyfill

- src/es-module-shims.js
Previously `<script type="module-shim">` tags appended to DOM when replacing the entire `<body>` tag using eg. [Turbolinks](https://github.com/turbolinks/turbolinks) would not be processed.
I have confirmed this patch resolves the issues I had with `es-module-shims` in a local Turbolinks enabled Ruby on Rails application.
I briefly looked at the test folder but failed to figure out how I could add tests for this behaviour. Seems like there are no tests for the MutationObserver currently (no tests failed when I attempted to remove the MutationObserver).
Let me know if there is a strong desire to test this diff. If so I'll need some help to get started.
> Support processing nested script / link tags in MutationObserver

- src/es-module-shims.js
This maintains an internal fetch cache when using the modulepreload polyfill to ensure that it does not race with the main source fetch calls in Firefox.
Verified that this resolves resolves the caching issue in Firefox described in https://github.com/guybedford/es-module-shims/issues/148.
> feat: preload polyfill fetch cache

- README.md
- src/common.js
- src/es-module-shims.js
- test/browser-modules.js
- test/fixtures/css-assertion.js
- test/fixtures/sheet.css
- test/test-chrome-noshim.html
- test/test-preload-case.html
- test/test.html
This adds support for polyfilling CSS module scripts, as well as the careful feature detection to only polyfill CSS modules as necessary by including a feature detection and only triggering the polyfill when there is CSS in the specific subgraph (unless in shim mode as per usual operation).
Support is also included for normalizing URLs in the stylesheet to be relative to the loaded stylesheet URL as per the spec.
Import assertions still do not actually perform the assertion in this project for now, although that may change in future.
> feat: support css module scripts & import assertions

- src/es-module-shims.js
- test/server.mjs
Fixes https://github.com/guybedford/es-module-shims/issues/157 ensuring that inline scripts properly opt-out of execution in the fallback case now when they don't hit the global fallback due to the new JSON / CSS module analysis pass.
> fix: polyfill fallback

- README.md
- src/es-module-shims.js
- test/browser-modules.js
- test/test.html
This implements re-triggering of the `readystatechange` and `DOMContentLoaded` events given that the polyfill can miss these attachments for userland libraries where changing those libraries to check the static readystate is not an option.
In the process static script ordering semantics are carefully implemented as well to fix ensuring that static module scripts always execute one after another in order while still fetching and processing in parallel.
An opt-out for the behaviour is provided by the init option `noLoadEventRetriggers`, as documented.
Resolves https://github.com/guybedford/es-module-shims/issues/161, https://github.com/guybedford/es-module-shims/issues/99.
> feat: load event refiring and careful static ordering

- src/es-module-shims.js
This should resolve https://github.com/guybedford/es-module-shims/issues/163.
I don't have a full replication of the case, so this will need further verification.
> fix: ensure preloads are always deduped

- README.md
- src/es-module-shims.js
- test/test-chrome-noshim.html
This implements polyfill hints as outlined in https://github.com/guybedford/es-module-shims/issues/150.
I ended up using the name `skip-shim="import-maps"` on the module script as I think this more closely matches what it actually does in that it ignores all other pollyfill processing of the given script tag when import maps are supported.
For now `import-maps` is the only value, but `css-modules` and `json-modules` will clearly be ones to add and any other new modules features in future are candidates as well.
> feat: skip-shim polyfill hints

- src/es-module-shims.js
- test/browser-modules.js
- test/runMochaTests.js
- test/test.html
Attempts to fix flakey mocha tests in Firefox 60.
Mocha is far more trouble than it is worth when we should just be importing tests via dynamic import and failing if they throw. All this work to support a buggy library with unclear conventions and timings just to get nice green ticks is getting ridiculous.
> Try fix mocha issues

- src/common.js
- src/es-module-shims.js
This resolves https://github.com/guybedford/es-module-shims/issues/169 where the polyfill of dynamic import would then try to polyfill its own injections resulting in an infinite loop crashing the browser.
> fix: fixup dynamic import polyfill recursion

- package.json
This adds an `"exports"` field to the package.json referencing the "main". This ensures the package is fully encapsulated.
> Add the exports field

- README.md
This updates the compat table to note we only support Edge 17+ per https://github.com/guybedford/es-module-shims/issues/68.
> Change compat to Edge 17+

- src/es-module-shims.js
Fixes https://github.com/guybedford/es-module-shims/issues/181.
With the new error handling changes global errors were propagating to `onerror` and the script load event but not to the console unhandled rejection.
Improved on 0.12 and made this an uncaught error instead of an unhandled promise rejection as well to more closely match normal script errors.
> fix: ensure global script errors reach console

- src/es-module-shims.js
This fixes up the fetch pool to preserve original ordering via first in first out instead of first in last out!
> fixup: preserve pool ordering

- src/es-module-shims.js
This reverts https://github.com/guybedford/es-module-shims/pull/144. After investigating turbolinks more thoroughly, it turns out script injections are separately applied to the head in https://github.com/hotwired/turbo/blob/c4891515645880ae1f9b4ee5757a8d730b89ac4e/src/core/drive/page_renderer.ts#L60 and in the body in https://github.com/hotwired/turbo/blob/c4891515645880ae1f9b4ee5757a8d730b89ac4e/src/core/frames/frame_renderer.ts#L48.
This is consistent with the fact that in HTML, setting the `body` `innerHTML` does not cause script execution.
#144 causes a huge amount of performance cost due to querying all mutations so this is a significant performance improvement.
> fix: revert nested mutation observers

- README.md
- src/dynamic-import-csp.js
- src/dynamic-import.js
- src/es-module-shims.js
- src/features.js
- src/options.js
- test/polyfill.js
- test/revoke-blob-urls.js
- test/runMochaTests.js
- test/shim.js
- test/test-csp.html
Most of these are minor perf improvements while simplifying the logic.
Changes include:
* Dynamic import map injections now support an `onload` event
* The "waitingForImportMaps" interval check is now no longer based on a regular timer, which should significantly reduce DOM polling performance issues.
* Dynamic imports always scan for new import maps first to ensure import maps promise attachment.
* Better polyfill mode opt-out for `importShim` / dynamic import. Dynamic import via `importShim` in both polyfill and shim mode now fully uses the native fallback whenever possible instead of still running through the shim functionality.
* DOM load events are now _always_ retriggered, this simplifies the assumption that domready will just call twice. One of the driving reasons for this is that …
> feat: miscellaneous polishing / perf

- package.json
- rollup.config.js
- src/dynamic-import-csp.js
- src/dynamic-import.js
This significantly improves the performance of the CSP build by using asm.js instead of plain JS for the execution from the latest es-module-lexer release.
> feat: asm.js csp build for performance

- src/dynamic-import-csp.js
- src/features.js
This fixes up the CSP build performance regressions by ensuring we use a dynamic import from the target module nonce context, instead of always using `<script>` injection. This brings performance roughly in line to the Wasm version.
> fix: csp perf via direct dynamic import

- src/common.js
- src/es-module-shims.js
When running a development build with `ESMS_DEBUG` enabled, it is useful to also force the shim paths. This enables an easy workflow for testing the polyfill performance under this option where it doesn't defer to the native loader but always does the source analysis and blob rewriting.
> feat: force shim paths under ESMS_DEBUG

- README.md
- package.json
- rollup.config.js
- src/es-module-shims.js
- src/features.js
- src/import-map.js
- test/test-polyfill-wasm.html
It turns out that in Safari, the asm.js build is actually faster than the Wasm build.
So since in Chrome and Firefox the compressed footprints are now equivalent AND the performance is identical, switching to the CSP build by default just makes sense - users shouldn't have to think about this stuff.
The win is then that iPhone / Safari performance then gets a ~25% speed improvement overall!
The Wasm build is still available and tested, but separately under `es-module-shims/dist/es-module-shims.wasm.js`. This will be 0.16 to be released shortly.
> feat: make the CSP asm.js build the main entry

- README.md
- src/es-module-shims.js
- test/base-href.js
- test/polyfill.js
- test/shim.js
This improves the ES Module Shims passthrough performance by entirely avoiding DOM processing when in polyfill mode and supporting all baseline features.
This includes:
* No preload fetches
* No DOM mutator attachments
* No script processing
* No import map processing
> feat: improve passthrough performance

- README.md
- src/es-module-shims.js
- src/options.js
- test/fixtures/es-modules/global1.js
- test/polyfill.js
- test/shim.js
This was still on the old JSPM and Pika CDNs. Removed the default, and just provided an example that covers `cdn.skypack.dev` and `jspm.dev` as illustrative.
> Disable skip option defaults

- src/es-module-shims.js
- test/polyfill.js
This fixes a bug in the native passthrough improvements implemented in https://github.com/guybedford/es-module-shims/pull/194.
When using `importShim()` directly, the only way to construct a contextual dynamic import (even just at the top level) is to fully reconstruct the resolver, thus we still need full knowledge of the import maps on the page.
> fix: importShim must still follow import maps even for passthrough

- src/es-module-shims.js
Fixes a typo in the recent lifecycle event refactoring from https://github.com/guybedford/es-module-shims/pull/197.
> fix: syntax error

- README.md
- package.json
- src/es-module-shims.js
- src/features.js
- src/options.js
- test/test-early-module-load.html
This is a way of working around the issue in https://github.com/WICG/import-maps/issues/248.
Instead of simply having the application not work in polyfill mode when there is eg a browser extension on the page injecting a module script before the import map, this will do a detection to see if there are any module scripts before the import maps, and if so kick into the polyfill mode automatically.
In addition this adds a new hook option `onpolyfill` that can be used to check when the polyfill is engaging. When passed via the JSON `<script type="esms-options">{ ... }</script>` the string value is taken to be the global function name of the hook to call.
> feat: still polyfill when early module loads stop import maps

- README.md
- src/options.js
- test/fixtures/json-or-js.js
- test/fixtures/template.jsx
- test/fixtures/transform.js
- test/fixtures/transformed.js
- test/shim.js
The fetch hook mistakenly got renamed to `fetchHook` due to actual JSON support stopping the fetch hook test from applying.
This fixes up the fetch hook test, reverts the naming, and updates the docs.
> fix: fetchHook test and name bug

- src/es-module-shims.js
Resolves https://github.com/guybedford/es-module-shims/issues/217.
//cc @hronro
> Fix sourcemapping regex

- src/es-module-shims.js
- test/fixtures/instance-case-a.js
- test/fixtures/instance-case-b.js
- test/fixtures/instance-case-common.js
- test/fixtures/instance-case.js
- test/polyfill.js
- test/test-csp.html
- test/test-polyfill-wasm.html
- test/test-polyfill.html
Resolves https://github.com/guybedford/es-module-shims/issues/219.
This was a result of the performance enhancement in https://github.com/guybedford/es-module-shims/pull/208 which stopped doing fine-grained polyfilling on a per-module basis, and instead duplicates module loads between pure native and pure polyfill modes.
The logic wasn't quite right on one of the codepaths, which has been updated based on the new principle that a top-level `<script type="module">` tag will be assigned to **either** the native loader or the polyfill loader (and the polyfill loader will always apply when the native loader fails). This does still mean that native modules that succeed in polyfill mode will not share dependency instances with polyfilled modules, and this remains an instancing footgun, but at …
> fix: Polyfill instancing bug

- package.json
- src/es-module-shims.js
Adds support for the `"async"` attributes on module scripts both in shim and polyfill modes, not causing that module script's execution to be delayed on previous module script executions per the HTML spec.
Fixes https://github.com/guybedford/es-module-shims/issues/216.
> feat: support async attribute dom ordering

- src/options.js
I got this error:
Which was thrown here:
So i tried to check how the nonce value was retrieved:
https://github.com/guybedford/es-module-shims/blob/b99eddfe33445cff16896f4353d66e3c7a001a0f/src/options.js#L17
Which violates the rules for accessing nonce: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_nonces_and_nonce_hiding
Changing the line from 
```ts
nonce = nonceElement.getAttribute('nonce');
```
to
```ts
nonce = nonceElement.nonce
```
seems to fix the issue.
> Fixed dynamic retrieval of nonce attribute 

- README.md
I discovered a small typo while following the instructions for configuring JSON module support (the error message correctly indicated which property was expected)
> doc: correct minor syntax error in CSS/JSON modules usage example

- src/features.js
An alternative approach to addressing Weixing Browser compatibility, first attempt here: https://github.com/guybedford/es-module-shims/pull/165
This version uses iframe.src and createObjectURL, which in theory should work anywhere es-module-shims itself does (since it's already used heavily internally), instead of document.write, which results in a lighthouse score hit and scary warning:
I don't have easy access to Weixing Browser to test this, so we'll probably need to roll a new release and ask for help from @xxgjzftd to try it out.
> Use createObjectURL & iframe.src

- src/es-module-shims.js
This fixes the trailing comment regex landed in #229 for Ruby 7 source maps support in Safari, ensuring that comments with only one character are fully supported.
> fix: trailing comment regex from #229

- README.md
- src/common.js
- src/es-module-shims.js
- src/options.js
- test/shim.js
This PR adds a new `enforceIntegrity` option, which when set to true will throw if module loads are attempted without integrity being set.
In addition this PR switches shim mode to using `modulepreload-shim` instead of `modulepreload` since when using shim mode in this way it would be desirable not to prime the main module cache for unnecessary performance. This PR also makes `modulepreload-shim` the only supported preload form in shim mode, although since this only affects preloading it is still a backwards compatible change.
In shim mode `enforceIntegrity` is then sufficient to provide strong execution integrity guarantees.
Some refactoring to reduce the footprint is also included in this PR.
> enforceIntegrity option, modulepreload-shim support

- README.md
- src/es-module-shims.js
- src/options.js
This updates the `onpolyfill` hook to apply when first executing polyfilled code instead of just on init, so when there is a real native code path that failed that the polyfill is kicking in to polyfill.
Then, the default hook contains a `console.info` message noting that the native error which will be present can be ignored.
Here's how that looks in Firefox:
Hopefully this will help avoid any production confusions.
> feat: onpolyfill note default

- src/es-module-shims.js
When propagating the load error, Safari loses the parse stack information if using `setTimeout(() => { throw e })` to create a window error.
Instead we use `console.error` to display the error message and for error hooking users will need to rely on the `onerror` hook instead.
I have verified that this definitely fixes parse error stacks in Safari.
> fix: Safari parse errors

- src/common.js
- src/es-module-shims.js
The fix in https://github.com/guybedford/es-module-shims/pull/238 ensuring proper parse errors for Safari caused Firefox stacks to break.
This branches using UA detection to achieve the best reporting per platform.
> fix: Firefox error stacks

- README.md
This was misleading because the option doesn't default to `true`.
> Fix default value of `enforceIntegrity` option documented in README

- src/es-module-shims.js
This is a minor follow-up to 76b18ba75273b2bd1330a9b418b100e686d06707 from https://github.com/guybedford/es-module-shims/pull/229 - that refactoring ended up separating the comment from the RegExp it was annotating. I've brought them back together and also fixed a typo: "Ruby 7" was used instead of "Ruby on Rails 7" (the former doesn't exist: [Ruby is currently on version 3](https://www.ruby-lang.org/en/downloads/releases/)). I also extended the comment with a link to the associated issue (https://github.com/guybedford/es-module-shims/issues/228) since I thought it could be helpful for anyone looking for additional context, but let me know if you don't want that.
> Fix typo and move comment about source map compatibility above the line it documents

- CHANGELOG.md
- src/common.js
Chrome 64 doesn't handle the absent catch binding, since it's such a minimal code change I was hoping to fix it in the source. Happy to hear your thoughts 🙂
> fix: optional catch binding for chrome 64

- src/common.js
- test/shim.js
I'm running into this because I'm overriding the old "dynamic" import map when user installs a new package with a new import map that contains old mappings as well as the new one.
I could do more processing on my side to avoid old mappings in the new import map but I think a more DX friendly solution would be to not complain in situations where the mapping hasn't really changed.
> Allow overriding a dynamic import map mapping to the same resolution

- src/es-module-shims.js
For dynamic CSS and JSON import, Chrome requires type assertions, that means it supports (1):
```js
import("foo.json", { assert: { type: "json" } })
```
but not (2):
```js
import("foo.json")
```
SystemJS supports both (it just ignores the assertion part).
Currently `es-module-shims` supports only syntax (2). Syntax (1) will be converted to something like this `importShim("foo.json", { assert: { type: "json" } }, "http://localhost:3000")` which results in an error.
This PR moves the assertion part to be to last argument which will be ignored so that the shims will support both syntaxes.
> feat: add support for dynamic import assertions

- src/common.js
- src/es-module-shims.js
This fixes the top-level URL resolution when using `import.meta.resolve` in an inline module script. It also fixes Safari UA detection and double slash (`//`) resolution support.
> fix: baseURI for inline scripts

- README.md
- src/es-module-shims.js
- test/fixtures/sheet.css
- test/test-polyfill.html
This fixes the URL normalization bug in https://github.com/guybedford/es-module-shims/issues/245 for CSS imports.
> fix: CSS imports normalization

- src/options.js
Instead of showing:
```
OK: "Uncaught TypeError" module failure has been polyfilled
```
This updates the polyfill message to:
```
OK: ^ TypeError module failure has been polyfilled
```
This is because Safari doesn't show the term "Uncaught" which might be confusing.
> feat: reword polyfill message to remove uncaught term

- src/es-module-shims.js
This tries to fix https://github.com/guybedford/es-module-shims/issues/255
1. Update `resolveDeps` so that dynamic imports will be converted the form `importShim(id[, assertion][, parentUrl])`
2. Update `importShim` to expect `parentUrl` if present will be the last argument
> fix: #255 importShim getting parentUrl

- src/es-module-shims.js
This improves the `Error: Unsupported Content-Type` error context to include the full URL, parent importer URL along with a message noting how to resolve the issue.
> feat: improve content type failure message

- .github/workflows/ci.yml
- chompfile.toml
- package.json
- src/dynamic-import.js
- src/features.js
- test/server.mjs
This implements an alternative to https://github.com/guybedford/es-module-shims/pull/227 avoiding the navigation event.
// cc @LarsDenBakker 
@lewisl9029 I'm not easily able to test this on Weixin browser, but I assume the approach should work there in it being a `document.write` restriction and not a `contentDocument` restriction.
This PR also includes the build system upgrade to Chomp.
> fix: alternative 227 implementation

- README.md
- chompfile.toml
- src/env.js
- src/es-module-shims.js
- src/resolve.js
- test/revoke-blob-urls.js
- test/shim.js
- test/test-revoke-blob-urls.html
This adds two new hooks to the configuration - an `onimport` hook which is called on each top-level import and that can do any async work, and a `meta(metaObj, url)` hook which allows customizing the import.meta object for all module sources.
This PR also updates `import.meta.resolve` to be synchronous. As an experimental feature this change is considered non-breaking since the status was indicated alongside the feature as experimental from the beginning.
The sync resolver is also made available globally via `importShim.resolve`.
Asynchronous resolve hooks will still be supported, but will then be deprecated in the next major.
This then fully aligns with the HTML sync import.meta.resolve function per https://github.com/whatwg/html/pull/5572.
> feat: import hook, meta hook, backwards-compatible sync resolver

- src/es-module-shims.js
- test/fixtures/test-nested-dynamic.js
- test/fixtures/test-rel-dynamic.js
- test/shim.js
Resolves https://github.com/guybedford/es-module-shims/issues/275 in supporting nested dynamic import structures, like `impor(new URL('./x', import.meta.url))` or even things like `import('./feature-' + (await import('feature')).name)`.
> fix: supported nested dynamic import structure replacements

- src/es-module-shims.js
Resolves https://github.com/guybedford/es-module-shims/issues/280 where:
```js
var fs;
if (isNode) {
fs = await import("fs");
} else {
fs = ... browser implementation ...
}
```
would fail when `fs` cannot resolve.
> fix: bug where non-existing dynamic import would fail polyfill execution

- src/features.js
es-module-shims creates an iframe to do feature
detection. However, if a site is using CSP then
this iframe is blocked unless the CSP config allows
frame-src to use blobs, which prevents es-module-shims
from running. In chrome that error looks like:
Refused to frame 'blob:http://localhost:3000/477a88e6-fb4c-48fd-a677-2ba7fb69fc45'
because it violates the following Content Security Policy directive:
"default-src 'self' https:". Note that 'frame-src' was not explicitly set,
so 'default-src' is used as a fallback.
In safari it looks like:
Refused to load blob:https://cors-test.herokuapp.com/12cecc46-329e-4791-a73b-4824852d1ad1
because it appears in neither the child-src directive nor the default-src
directive of the Content Security Policy.
To prevent this, I've updated `feature.js` to set a …
> Add nonce to feature detection iframe

- src/es-module-shims.js
- test/test-preload-case.html
This fixes the bug https://github.com/guybedford/es-module-shims/issues/286, where the [retriggering of the readystatechange](https://github.com/guybedford/es-module-shims#no-load-event-retriggers) event would fire too early, instead of waiting on the ES module scripts when these scripts were detected too late in the loading process. 
In addition some further event handling cleanup is included.
> fix: retriggering of readystatechange and DOMContentLoaded events

- README.md
- src/env.js
- src/es-module-shims.js
- src/features.js
This updates es-module-shims's import map detection to use the `HTMLScriptElement.supports('importmap')` API if available.
In addition this resolves https://github.com/guybedford/es-module-shims/issues/284, in turn adding support for polyfilling `HTMLScriptElement.supports('importmap')` support if the polyfill kicks in.
> feat: utilize and polyfill HTMLScriptElement.supports

- test/test-csp.html
Previously there was no default set so
any files could be loaded from anywhere
(except for scripts which were allow-listed).
This changes the csp so that by default
only localhost can be used. This should
detect issues like #290.
> Set default csp policy

- src/es-module-shims.js
- src/features.js
- test/polyfill.js
- test/test-csp.html
This fixes a typo in the case of a module with only an `import.meta` polyfill.
In addition we automatically treat `import.meta` and dynamic imports as supported if the browser supports import maps, since all browsers that support import maps support import meta (there were two compat cases where dynamic imports were supported before import meta - Opera and Safari). This results in less unnecessary feature detection work.
> fix: import.meta polyfill, better feature detection

- README.md
- src/dynamic-import.js
- src/env.js
- src/es-module-shims.js
- src/features.js
The purpose of this commit is to enable the usage of `es-module-shims` in module web workers, which at the moment are supported in Chrome based browsers and Safari > 15. As you know, in Firefox the support is still missing.
However, web workers cannot access objects like `document` or `window`. Therefore, I had to do the following changes in `es-modules-shims` code:
- add some simple pieces of code that check whether `document/window` exists before doing something with the `document/window` object; it's not elegant, but these checks are necessary;
- add a function that computes the `baseUrl`. In fact, this function was already defined in `es-module-shims` version `0.4.7`.
- I also added a new function `setImportMap` which can be used to set the import map from outside (obviously). This …
> Enable es-module-shims usage in web workers

- index.d.ts
Updating the TypeScript types to include recent additions. Also attempts to accurately represent the types in the `registry` map, though that could use some extra scrutiny.
> Improve TypeScript types

- src/dynamic-import.js
- src/env.js
- src/features.js
This fixes CSP support with a number of enhancements:
* Fixing the case where `HTMLScriptElement.supports('importmap') === false` skips the import map detection as it should have been doing already
* Updating the internal feature detections to use blobs instead of data URIs so that it's only necessary to add `blob:` to the policy and not both `blob:` and `data:` for easier usage
* The document.write path in the iframe feature detection is again modified to attempt a srcdoc approach first before falling back to document.write. This avoids a bunch of warnings and possible issues with using document.write by default. Hopefully this finally gets us to a middle ground on that case.
* A new clear error message is thrown by the Wasm build when eval is not supported, to avoid possible obscure …
> feat: simplify feature detections csp policies

- src/features.js
- test/runMochaTests.js
- test/shim.js
- test/test-shim.html
Fixes a bug in the new import map detection from 1.5.7, introduced in https://github.com/guybedford/es-module-shims/pull/302.
Resolves https://github.com/guybedford/es-module-shims/issues/303.
> fix: safari import maps detection

- src/env.js
- src/es-module-shims.js
Fixes https://github.com/guybedford/es-module-shims/issues/305 in ensuring that the shim mode detection and `importMapSrcOrLazy` checks are done early before ES Module Shims injects its own scripts, which were interfering with the results in the case of an import map in the body of the HTML.
> fix: early shim mode detection

- test/server.mjs
- test/shim.js
I have something already running on port 8080, so being able to say `WATCH_MODE=true CI_PORT=0 node test/server.mjs test-shim` is practical.
The default is still port 8080.
Also narrowing down the test server to only localhost instead of all addresses.
Found while working on #311.
> Tests can run on any HTTP port, and auto-allocate a port.

- test/server.mjs
`start()` is executed on timeout.
> fix: retries in tests broke from #312.

- src/dynamic-import-csp.js
- src/es-module-shims.js
- src/features.js
Fixes an initialization bug introduced in https://github.com/guybedford/es-module-shims/pull/317 that would inhibit polyfilling when es-module-shims loads after DOMContentLoaded.
Feature detections are kept early, but done in an iframe so that any module loads will not interfere with the main frame map phases.
> fix: polyfill initialization ordering bug from #317

- chompfile.toml
- src/es-module-shims.js
- src/features.js
- test/server.mjs
This provides some follow up on the recent timing work from #320:
* The iframe feature detection promise is fixed to properly resolve on feature detection completion
* DOMContentLoaded should no longer fire twice when the polyfill doesn't kick in
* The additional DOM parse in DOMContentLoaded is removed since we already have init and readystatechange parses as well as mutation observers, DOMContentLoaded should provide no new timing interception point we don't already cater to
* `processImportMaps` and `processScriptsAndPreloads` are combined into the same function as a refactoring
> fix: timing fix follow-ups from #320

- src/es-module-shims.js
- src/features.js
- test/fixtures/once.js
- test/polyfill.js
- test/test-csp.html
- test/test-polyfill-wasm.html
- test/test-polyfill.html
This adds some better checks for reading streaming `<script>` tags for import maps and inline scripts to ensure the page is fully loaded before they are executed.
We also add a better error message for when import map parsing fails, logging the JSON error alongside the map that was being parsed.
A polyfill engagement check and fix is also added for when Firefox import maps support lands unflagged.
> feat: handle streaming import maps, better import map errors

- src/dynamic-import.js
- src/env.js
- src/features.js
- test/frame.html
- test/server.mjs
- test/test-iframe-sandbox.html
This resolves https://github.com/guybedford/es-module-shims/issues/324 in ensuring that es-module-shims can be supported itself in a sandboxed iframe.
We update the iframe communication to use postMessage, and ensure that the feature detection source blobs are generated in the frame doing the feature detection.
> fix: iframe sandbox detections

- src/es-module-shims.js
- test/fixtures/es-modules/tdz.js
- test/shim.js
The cycle hoisting work in https://github.com/guybedford/es-module-shims/pull/311 opened up a new class of TDZ errors, where hoisted bindings that are in TDZ would throw at access in this hoisting.
This resolves https://github.com/guybedford/es-module-shims/issues/331, as described there, by wrapping the early cycle hoisting process in a try-catch to avoid these errors. Because the post-update hook will still catch the binding updates nothing is lost. More fine-grained hoisting approaches are still possible based on better analysis in future, but let's see those cases come up first.
> fix: early hoisting tdz errors

- README.md
- src/env.js
- src/es-module-shims.js
Adds a new array value type to the `skip` option, corresponding to a list of exact URLs to skip or URL paths to skip. Can be relative or absolute URLs.
> feat: skip array option

- src/es-module-shims.js
The casing of the `<script>` element's [crossorigin][] and [referrerpolicy][] HTML _attributes_ differ from the casing of [HTMLScriptElement.crossOrigin][] and
[HTMLScriptElement.referrerPolicy][] _properties_.
Prior to this commit, the implementation erroneously attempted to read values from the _properties_ through names cased as if they were _attributes_.
This commit replaces the lower-cased accesses with camelCased ones.
[crossorigin]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-crossorigin
[referrerpolicy]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-referrerpolicy
[HTMLScriptElement.crossOrigin]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement#instance_properties
[HTMLScriptElement.referrerPolicy]: …
> Change property readers to camelCasing

- src/es-module-shims.js
- test/polyfill.js
- test/test-csp.html
- test/test-polyfill-wasm.html
- test/test-polyfill.html
Resolves https://github.com/guybedford/es-module-shims/issues/356 in ensuring that under baseline passthrough we always avoid domcontentloaded and readystatechange event retriggering.
> fix: domcontentloaded duplication

- .github/workflows/ci.yml
- README.md
- src/es-module-shims.js
- test/server.mjs
This fixes the case where an inline `<script type="module">import('./rel.js')</script>` would execute as a blob URL unexpectedly since the paths for a dynamic import and an inline module execution are currently overlapping.
Instead, in the case of an inline module execution, we explicitly avoid reexecution.
When dynamically importing an existing module with `importShim('./path.js')`, we can still risk reexecution but that is because we are using the shim loader instance specifically in this case.
This should avoid mixups like in https://github.com/guybedford/es-module-shims/issues/355. Some documentation updates are also included.
> fix: native inline deduping

- chompfile.toml
- rollup.config.js
- src/es-module-shims.js
- src/features.js
- test/test-shim-map-overrides.html
- test/test-shim.html
This PR fixes #363, where the feature detection script in Safari in some special cases, handling undefined return from feature detection possibly due to security policy, and also more carefully guarding the Wechat fallback path.
Includes a debug build for diagnosing similar cases in future where we don't necessarily have a replication but need detailed debugging information.
> fix: feature detection, add debug build

- package.json
- src/features.js
I was also running into intermittent feature detection failures similar to the ones mentioned in https://github.com/guybedford/es-module-shims/issues/368 once I upgraded to 1.7.1 on https://reflame.app, so I made a custom build with some additional logging on the message callback function and found a pretty big clue:
Looks like the root of the issue might be that we're not verifying the source of the message, so anything that calls postMessage before es-module-shims (in this case the react dev tools extension) can cause feature detection to fail, often non-deterministically due to races.
Looking at this [previous related issue](https://github.com/guybedford/es-module-shims/issues/363), I think this is the more likely cause for that one too rather than some security policy (i.e. something …
> Verify feature detection message

- src/es-module-shims.js
- test/fixtures/es-modules/with-source-url-and-source-mapping-url.js
- test/shim.js
Hey there! I started making use of sourceURL comments to preserve breakpoints across updates in [Reflame](https://reflame.app), and discovered that shim mode seems to ignore the existing sourceURL and adds its own if both sourceURL and sourceMappingURL exists.
I've captured this behavior in a new test. Here's the existing behavior:
(note the 2 sourceURLs)
Here's the new behavior after my fix:
A few things contributed to the existing behavior:
- The regex we use matches for end of string, so will never actually match a sourceURL comment that's not at the last line
- `resolvedSource.replace` only executes once and only replaces the first instance, so it could never properly handle the case where both exist.
My fix splits the previous regex into 2, one for sourceURL and one for …
> Respect existing sourceURL when both sourceURL and sourceMappingURL exists

- index.d.ts
- package.json
Base on assumption `./dist/es-module-shims.js` `./dist/es-module-shims.debug.js` `./dist/es-module-shims.wasm.js` have same type.
Verified with `npm pack` and `https://arethetypeswrong.github.io`,
Base on assumption `window.esmsInitOptions = {}` is valid, like [example](https://github.com/guybedford/es-module-shims#polyfill-features)
```patch
* Enable polyfill features.
* Currently supports ['css-modules', 'json-modules']
*/
-  polyfillEnable?: string[];
+  polyfillEnable?: Array<'css-modules' | 'json-modules'>
```
> fix #381 #382

- src/es-module-shims.js
- test/shim.js
Hey there!
(I couldn't find any notes on contributing so I assumed that PRs are welcome but if not, no worries)
I want to filter response errors throw in `es-module-shims` based off some criteria of their response. I find parsing the error message a bit brittle but I _could_ get the information from there. Before doing that I wanted to suggest sub-classing the `Error` class with a `ResponseError` which includes the actual response and then throwing that error when a response error occurs.
What do you think? I added a single test but I can add some more to increase confidence.
> Add response to response errors

- index.d.ts
- src/env.js
Fixes #384.
This change starts accepting a regular expression proper as a `skip` option. This seems to have been indicated by the existing types and counter-intuitively the types that are actually accepted aren't represented in the TypeScript declaration.
This pull request adds the `string[] | string` types to the `skip` property in the options type and creates a `skip` wrapper in case the variable passed in is a regular expression.
> Fix the `skip` option

- README.md
It looks like Firefox supports dynamic import in Worker Contexts as of ~113. See [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1540913) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#browser_compatibility)
> Updated Firefox stats

- README.md
- resources/testharness.js
- src/env.js
- src/es-module-shims.js
In https://github.com/guybedford/es-module-shims/pull/413, in order to pass the web platform tests, retriggering the Window load event was enabled by default.
To avoid that being a breaking change on release, this adds a new option - `globalLoadEventRetrigger` to enable this feature conditionally, so that we can instead turn it on by default in the next major instead.
> feat: explicit globalLoadEventRetrigger option

- README.md
- src/es-module-shims.js
Resolves https://github.com/guybedford/es-module-shims/issues/419 in ensuring the progressive binding update interleaving for cycles only applies after a declaration import.
> fix cycle binding updates for expressions

- README.md
- src/es-module-shims.js
- src/resolve.js
- test/shim.js
- test/test-shim.html
This adds support for picking up integrity from the import map itself when polyfilling.
Before this feature is shipped in Chrome, this will mostly be useful for shim mode to ensure full integrity for all modules, but once it ships it allows us to ensure that the polyfill also validates integrities provided via the import map.
This implementation supports integrity in import map extensions with multiple import maps, providing an error when the integrity is overridden so that the first integrity in the import map for a given URL is always authoritative.
Explicit preload and script integrities still override the import map integrity value.
This feature is fully compatible with the existing `enforceIntegrity` option for ensuring that all modules are loaded with integrity.
//cc @yoavweiss this …
> feat: support importmap integrity

- README.md
According to [`caniuse`](https://caniuse.com/import-maps) it’s 91% of all users, and 93% of tracked.
Pretty nice!
> State current native support stands at 91%

- src/es-module-shims.js
- test/fixtures/es-modules/no-imports.js
Resolves https://github.com/guybedford/es-module-shims/issues/436 where we would bail on bad source map resolutions.
> fix: dont bail on bad source map resolution

- README.md
- src/env.js
- src/es-module-shims.js
- src/features.js
- src/resolve.js
- test/fixtures/css-assertion.js
- test/fixtures/json-assertion.js
- test/polyfill.js
- test/shim.js
- test/test-early-module-load.html
- test/test-polyfill.html
This implements a polyfill for the new multiple import maps feature in Chrome (https://groups.google.com/a/chromium.org/g/blink-dev/c/4JWXZilDG6w).
I've tested this in Canary and can confirm it works correctly with the baseline passthrough mode engagement.
Multiple import maps actually flip the logic on the previous native subgraph passthrough feature that was formerly disabled in https://github.com/guybedford/es-module-shims/pull/208. With multiple import maps it is now possible to start out on baseline import maps support fully on the native loader, but then later on switch into polyfilling some graphs as needed if multiple import maps are later used.
This PR supports this new ability to "swich off" baseline passthrough as soon as multiple import maps come into play, and then in order …
> feat: polyfill multiple import maps

- README.md
- src/env.js
- src/es-module-shims.js
This implements the version 2 deprecation paths:
* `globalLoadEventRetrigger` is now on by default
* Support for an async resolve hook is removed
> deprecate: globalLoadEvent, async resolve

- resources/testharness.js
- src/es-module-shims.js
- test/polyfill.js
This resolves a bug where the polyfill checks for whether a given module needs to be polyfilled were not being properly proagated in cycles. The resolution is to propagate the checks on the second graph pass not the first, so that cycle edges are fully included.
This bug was exposed by the new passthrough behaviour in the 2.0.0 version, and this now fixes for example polyfilling JS/Wasm cycles with passthrough.
> fix: resolve cycle handling for polyfill checks

- src/es-module-shims.js
Fixes another 2.0.0 regression where the `processScriptsAndPreloads` code which assumes a document must always be guarded by `hasDocument`.
> fix: support in environments without a document

- README.md
- src/es-module-shims.js
- test/shim.js
This removes the mutation observer on the body, which would not attach if the body had not already been created when es-module-shims is loaded.
While browsers support scripts being anywhere, we can take a strict polyfill policy that only head injections are supported.
Resolves https://github.com/guybedford/es-module-shims/issues/451.
> fix: add mutation observer only to head not body

- src/es-module-shims.js
- test/polyfill.js
- test/test-csp.html
Resolves https://github.com/guybedford/es-module-shims/issues/454, testing and ensuring that a top-level import attribute case can be polyfilled in `importShim()` calls.
> Fix top-level CSS/JSON direct import polyfill

- chompfile.toml
- package.json
- src/es-module-shims.js
- test/test-ts.html
- test/typescript.js
This adds support for an inline:
```
<script type="module" lang="ts">
export const typescript: boolean = true;
</script>
```
TypeScript support when combined with enabling the new TypeScript feature.
In addition error messages are improved, Amaro is updated, and Amaro options are refined.
> feat: add support for inline typescript

- chompfile.toml
- src/es-module-shims.js
- test/test-ts.html
- test/typescript.js
This fixes the edge case where the TypeStripping has no work to do and we end up with double execution - instead ensuring that we only reexecute when truly needed.
> fix: support ts passthrough for no typestripping

- src/es-module-shims.js
Fixes a bug where the "module errors are polyfilled" message would not show for top-level inline TypeScript polyfill cases.
> fix: always show polyfill message for typescript

- README.md
As per the conversation at the CG meeting. There're more instances that I'm not sure about, but this fixes the `README`, which is where I got confused from.
> Make Wasm instantiation synchronous

- README.md
This switches back to the `await WebAssembly.instantiate(...)` advice due to the 8MB warning message we still get (pending https://issues.chromium.org/issues/398265337).
//cc @tomayac
> Revert #466 readme change

- README.md
- src/env.js
- src/es-module-shims.js
- src/features.js
Currently we have one main `wasm-modules` feature, this splits this feature into separate `wasm-module-sources` and `wasm-module-instances` features which can be enabled independently.
This way, setting `wasm-module-sources` will enable Wasm modules without instance support, allowing baseline passthrough on the upcoming source phase integration in Chrome.
> feat: split wasm-modules into wasm-modules-sources and wasm-module-instances

- README.md
- package.json
- src/env.js
- src/es-module-shims.js
- test/fixtures/test-defer-dynamic.js
- test/fixtures/test-defer.js
- test/polyfill.js
- test/test-csp.html
- test/test-polyfill-wasm.html
- test/test-polyfill.html
This adds support for the new `import defer` proposal as a form of syntax stripping in the polyfill.
All we do, is that when the `import-defer` feature is enabled, we replace `import defer * as ns from 'foo'` with `import * as ns from 'foo'`.
This can enable a useful polyfill for defer though:
* Use modern `import defer` syntax for modern browser users with defer support, getting the performance benefits.
* On older browsers without this support, module loading fails on this syntax error.
* This syntax error gets polyfilled via this simple stripping from es-module-shims, allowing the app to fully work on older browsers.
// cc @nicolo-ribaudo for reference
> feat: support import defer polyfill

- README.md
- src/env.js
- src/es-module-shims.js
- src/features.js
This PR enables JSON Modules by default in es-module-shims, allowing applications to polyfill this syntax without needing it to be explicitly enabled as a feature.
JSON modules have 85% browser support now, so most browsers will get baseline passthrough under this default enabling.
One repercussion though is that since JSON modules aren't implemented in Firefox, applications will always have their graphs analyzed for JSON usage.
To avoid this, it could be worth updating this PR to also support a new `polyfillDisable` option supporting `polyfillDisable: ['json-modules']` so that passthrough can still happen in Firefox when users know the application won't use JSON modules. I'm not sure if the benefits outweigh the costs for that yet though.
> feat: enable json-modules by default

- README.md
- src/env.js
- src/es-module-shims.js
- src/features.js
- test/test-csp.html
- test/test-polyfill-wasm.html
- test/test-polyfill.html
CSS import attributes, even though only in Chrome, are already at over 70% usage. It makes sense to enable them by default at this point.
This deprecates the `css-modules` option, just like https://github.com/guybedford/es-module-shims/pull/478 did for `json-modules` and now makes css modules part of the baseline.
Hopefully Safari and Firefox support will be coming further here, but in the mean time, this polyfill can help.
> feat: support CSS module imports by default

- rollup.config.js
- src/env.js
- src/es-module-shims.js
This fixes bugs that can occur when there are multiple instances of es-module-shims on the same page. We add an early exist when es-module-shims has previously been registered on the page. The reason for these conflicts is the `script.ep === true` check we use to determine processed scripts. A random attribute or symbol would avoid this, but we don't need to support multi-processing.
This also fixes up some event listener handling as well - ensuring we properly unregister event listeners on the page and fixing up a case where DOMContentLoaded wasn't correctly refiring.
> feat: support multiple instances, fix ready listeners

- README.md
- src/env.js
- src/es-module-shims.js
- src/hot-reload.js
- src/resolve.js
- test/fixtures/hotreload-accept-dep.js
- test/fixtures/hotreload-parent.js
- test/fixtures/hotreload.js
- test/fixtures/json-assertion.js
- test/fixtures/test.ts
- test/hot.js
- test/shim.js
- test/test-hot.html
- test/typescript.js
This implements the `import.meta.hot` API from Vite (https://vitejs.dev/guide/api-hmr.html).
The hot reloader is implemented as an extension using initialized hooks that executes before es-module-shims.
In addition this PR adds support for `nativePassthrough: false` to disable native passthrough, which is set automatically when enabling hot reloading.
> Hot reloading support via import.meta.hot

- README.md
- src/es-module-shims.js
- test/fixtures/module-dynamic.js
- test/fixtures/module-static.js
- test/test-double-polyfill.html
- test/test-sp-exported-names.tentative.html
- test/test-sp-wasm-js-cycle.tentative.html
This implements https://github.com/nodejs/node/pull/57525 in supporting `WebAssembly.Global` unwrapping on exports while retaining complete interop on imports through the weakmap namespace / instance relation.
This PR doesn't polyfill the weakmap as `WebAssembly.namespaceInstance()` currently although that would be an easy addition in future.
> feat: support unwrapped WebAssembly.Global exports

- README.md
- rollup.config.js
- src/env.js
- src/es-module-shims.js
- src/resolve.js
Adds the hard version protections suggested in https://github.com/guybedford/es-module-shims/issues/484 - freezing the `importShim` object on the global and also freezing its properties.
I would still like to verify before landing this:
1. The shim mode switch is definitely necessary. I would have thought the `ep` markers would have been conflict-avoiding here therefore this would be unnecessary.
2. The `defineValue(self, '_d', undefined)` thing - what version this is deconflicting with and why.
> feat: hard multi-version protections

- src/env.js
- src/es-module-shims.js
- src/features.js
I don't think we should be writing this global value in a way that can't be changed. I feel bad enough making `window.importShim` unwriteable.
What setting this does, is force the dynamic import check in older versions of ES Module Shims to fail - so that those old versions will think that dynamic import is not supported when in fact it is. This would not disengage the polyfill though it would in fact actually result in the polyfill polyfilling dynamic import and then using a dynamic import shim.
Therefore I cannot see how this would functionally disable an older version of ES Module Shims, short of there being very specific logic around the change in polyfill behaviours when it thinks dynamic import is not supported when it is.
//cc @frandiox I think I may need to revert this one …
> fix: remove _d override

- chompfile.toml
- package.json
- src/env.js
- src/es-module-shims.js
- src/hot-reload.js
- test/fixtures/json-assertion.js
- test/hot.js
- test/polyfill.js
- test/shim.js
This PR includes some miscellaneous changes for a 2.5.0 release:
* Hot reloading bug fixes
* Amaro patch update
* TypeScript compilation logs in the debug build
* TypeScript compilation warning log to avoid production usage
* Workarounds for Firefox crash on JSON reexports (https://bugzilla.mozilla.org/show_bug.cgi?id=1965620)
> fix: hot reloading, amaro updates, TypeScript log, Firefox crash

- README.md
- chompfile.toml
- index.d.ts
- src/core.js
- src/env.js
- src/hot-reload.js
- test/frame.html
This adds support for a new `source` hook that can return `{ url, source, type }` where `type` can be any of `js`, `css`, `json`, `ts`, `wasm`, and `source` can be a source text or `WebAssembly.Module`.
This feature allows the implementation of virtual module sources in the loader useful in sandboxing scenarios without needing to use a nested blob URL layer.
Usage example is:
```html
<script>
const virtualFs = {
'index.js': `import './src/dep.js';`,
'src/dep.js': 'console.log("virtual source execution!")'
};
esmsInitOptions = {
source (url, fetchOpts, parent, defaultSourceHook) {
// Only virtualize sources under the URL file:///virtual-pkg/ (i.e. via
// `import('file:///virtual-pkg/index.js)`.
if (!url.startsWith('file:///virtual-pkg/')) return defaultSourceHook(url, fetchOpts, parent); …
```
> feat: Source Hook

- src/core.js
- src/env.js
Fixes: [#500 SharedWorker "TypeError: handler is not a function"](https://github.com/guybedford/es-module-shims/issues/500).
Added a backup handler using a timeout to defer execution since neither `requestIdleCallback` or `requestAnimationFrame` are available in a shared worker context.
> Backup handler for shared worker

- src/core.js
- test/fixtures/json-proto.js
- test/fixtures/proto.json
- test/shim.js
```js
const json = JSON.parse('{"__proto__": "a"}')
console.assert(json.__proto__ === "a")
const js = {"__proto__": "a"}
// different behavior from json!
console.assert(js.__proto__ === Object.prototype))
```
> fix json modules with keys named "__proto__"

- src/core.js
- src/env.js
- src/hot-reload.js
the hot reload feature (i think) introduced some import cycles. this takes them back out.
> remove internal import cycles
